environment:
   APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
   APPVEYOR_SSH_BLOCK: true
 
init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - sh: sudo apt-get -yqq install virt-what
  - sh: sudo virt-what

test_script:
# remove NVM
  - rm -rf $HOME/.nvm/
  - export NVM_BIN=
  - unset -f nvm
# install 6.7.0 in system
  - sudo apt-get -y remove nodejs
  - curl -sflL -O https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.7.0-1nodesource1~xenial1_amd64.deb
  - sudo apt-get -y install rlwrap
  - sudo dpkg -i nodejs_6.7.0-1nodesource1~xenial1_amd64.deb
   
#  - nvm install 6.7.0
  
  - node --version
  - command -v node
  - npm --version
  - command -v npm

  - npm install -g npm@5.6.0  

  - node --version
  - command -v node
  - npm --version
  - command -v npm

build: off
